### ISSUE TITLE
flobby not compatible with new zerok lobby protocol

### ISSUE THREAD

**Issue by Jamanno** [cleanrock/flobby#18]
Will it be compatible? :-)
maybe add both protocols?

**Comment by cleanrock** [comment]
I hope ZKL on Linux will be good enough.

**Comment by cleanrock** [comment]
zerok branch created, so far you can login and see users and battles, not usable for playing or chatting yet

**Comment by cleanrock** [comment]
channel and private chat implemented

**Comment by cleanrock** [comment]
fixed by a72974c
