### ISSUE TITLE
possible problem with downloading engine versions?

### ISSUE THREAD

**Issue by abma** [cleanrock/flobby#19]
i've removed a hack in upq/api.springfiles.com which possible breaks downloading of engines with pr-downloader because engine check fails:

https://springrts.com/phpbb/viewtopic.php?f=11&t=33355&p=568882#p568882

this hack was added because zero-k lobby never implemented the check about engine version correctly.

idk what flobby sends to pr-downloader, reimplementing zero-k behaviour would mean to search for this:

http://api.springfiles.com/?springname=98.0.1-178-g18487b4*&category=engine_linux64

(just remove everything after space in version and add a wildcard to the search string)

**Comment by cleanrock** [comment]
Thanks for reporting, download actually works thanks to 63325a5 but start of spring seem broken, seems i now get space in extracted engine dir.

**Comment by abma** [comment]
oO in other words: spring doesn't start in a dir with space?

**Comment by cleanrock** [comment]
flobby did not support starting engines in paths with spaces, i will commit a quick fix soon.
Some day we should fix so that pr-downloader don't use spaces when it extracts engine, no hurry though since it will probably break something else :).
