### ISSUE TITLE
flobby doesn't build with newest arch boost libs

### ISSUE THREAD

**Issue by Jamanno** [cleanrock/flobby#20]
** I  rebuild flobby of course

[penna@powersau flobby]$ flobby -z
flobby: error while loading shared libraries: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory
[penna@powersau flobby]$ 
[penna@powersau flobby]$ 
[penna@powersau flobby]$ pacman -Ss boost
extra/boost 1.58.0-1 [installed]
    Free peer-reviewed portable C++ source libraries - development headers
extra/boost-libs 1.58.0-1 [installed]
    Free peer-reviewed portable C++ source libraries - runtime libraries

**Comment by cleanrock** [comment]
You did not rebuild thoroughly enough.
This is a situation where you should rebuild from scratch or at least rerun cmake, this should be obvious seeing flobby trying to open 1.57 when you just installed 1.58.
