### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by fratcn** [cleanrock/flobby#27]
notice the flobby make no sound ,why?

**Comment by Jamanno** [comment]
you can do that via: Settings -> Sound
There add something like this. The same command should work on command line, so you need to install commandline player like ogg123 or play as used beneeth.
"play /usr/share/sounds/freedesktop/stereo/device-added.oga"

so if you can play the sound from command line, just copy that command to Sound settings from flobby.

**Comment by fratcn** [comment]
well,thank u.
