### ISSUE TITLE
flobby cannot list develop engine from bleeding edge host

### ISSUE THREAD

**Issue by Jamanno** [cleanrock/flobby#29]
D-12:46:21-Model.cpp:249] runProcess: '/home/penna/games/bin/pr-downloader --download-engine "101.0.1-179-g5944ba1*"'
D-12:46:21-Model.cpp:258] runProcess logFile: '/home/penna/.cache/flobby/flobby_process_pr-downloader.log'
D-12:46:21-Model.cpp:263] runProcess system(): '/home/penna/games/bin/pr-downloader --download-engine "101.0.1-179-g5944ba1*" >> /home/penna/.cache/flobby/flobby_process_pr-downloader.log 2>&1'
D-12:46:26-Model.cpp:278] processDone:12, 0
D-12:46:26-Model.cpp:886] refresh sync:1

it is in .spring/engine
but flobby does not list it in settings-> engine

**Comment by cleanrock** [comment]
Are you sure 101.0.1-179-g5944ba1 exist for Linux ?
Try http://api.springfiles.com/?springname=101.0.1-179-g5944ba1*&filename=&tag=&sdp=&category=
When i try to download 101.0.1-179-g5944ba1 with latest flobby/pr-downloader download of engine fail.

**Comment by Jamanno** [comment]
yes. It downloaded it. I have the full engine in my usual engine folder
