### ISSUE TITLE
tabbing user in battle room tabs botnames as priority and general tabbing broken

### ISSUE THREAD

**Issue by Jamanno** [cleanrock/flobby#32]
e.g.:
[SC]Nicolas is the nickname and his bots:
Bot_2,[SC]Nicolas,Chicken: Suicidal

nic tabs auto the bot... other tab behaviour are strange too and you cannot tab through possibilities.

**Comment by cleanrock** [comment]
I fixed excluding AIs/bots and i am thinking about presenting a gui list (small menu) if there are multiple matches, this would force the user to select one entry with arrows/enter, do this sound good ? If not, what do you propose ?

**Comment by Jamanno** [comment]
nicest tabbing I had so far is in irssi.
You can tab through possible nicks if you reached last nick of possible nicks it continues from beginning..
