### ISSUE TITLE
Chat escaping

### ISSUE THREAD

**Issue by rlcevg** [cleanrock/flobby#36]
Can't type '\n' in chat - translates to new line.
Using AUR build, flobby-git-0.2.98.gee35f93-1

**Comment by cleanrock** [comment]
I am genuinely curious to know why this is an issue for you ?

**Comment by rlcevg** [comment]
There was a case: I wrote instruction for user and it included path to file like
"SkirmishAI\Circuit\config\normal.json"
The thing that appeared on my screen after sending text is
```
11:58 lamer: SkirmishAI\Circuit\config
ormal.json
```
That seems wrong, and hurts my eyes.
