### ISSUE TITLE
Strange re-sizing behavior

### ISSUE THREAD

**Issue by Alzarath** [cleanrock/flobby#38]
Resizing the middle separator is quite strange. Much of the left side and the entire upper right area seems to ignore it. The upper-right area and bottom area also seem to over-lap things.

[Imgur album](http://imgur.com/a/eX8Mp)

**Comment by cleanrock** [comment]
I will try improve some things in these areas but keep in mind that flobby is best experienced by setting a good layout when maximized and keep it that way (flobby will remember window size and layout on next start).

**Comment by Jamanno** [comment]
I agree on that. And you have to reorder every single chattab-

**Comment by Jamanno** [comment]
I tested it and it works. You only have to resize it one time. Thanks!!! Because with tilded window managers it happens sometimes that you resize everything with one accidently pressed shortcut
